#!/usr/bin/env bash
#-*- mode: sh -*-

export PROJECT_ROOT=$(pwd)
export PATH=$PROJECT_ROOT/env:$PATH

function build() {
    if [ ! -f env/build ]; then
        mkdir -p env/build
    fi

    gcc -std=c11 -pedantic-errors -fextended-identifiers -g -x c -o env/build/run -D GS_RASTER_DEBUG main.c raster.c -lm `sdl2-config --cflags --libs`
}

function run() {
    if [ -f env/build/run ]; then
        env/build/run "$@"
    fi
}

function debug() {
    if [[ "-h" == $1 ]] || [[ "--help" == $1 ]]; then
        echo "Usage: debug [parameters]"
        echo
        echo "parameters: Anything specified here will be passed to the running program"
        echo
        return
    fi

    local debugger=`which kdbg`
    if [[ -f env/build/run ]] && [[ ! -z "$debugger" ]]; then
        $($debugger env/build/run -a "$@")
    fi
}
